### ISSUE TITLE
macOS version

### ISSUE THREAD

**Issue by karlhorky** [panta82/do-not-disturb-during-zoom#1]
Hi there, thanks for this!

I'm on macOS, so I adapted your script to work with macOS here: https://github.com/karlhorky/do-not-disturb-during-zoom-macos

Would you be interested in bringing these changes into the main repository here?

**Comment by karlhorky** [comment]
This currently relies upon the script from @tiiiecherle at https://github.com/sindresorhus/do-not-disturb/issues/9 because the `do-not-disturb` npm package doesn't yet work for macOS Big Sur (11.1), but I will switch back to `do-not-disturb` as soon as possible...

**Comment by panta82** [comment]
Hey, I took a quick look over what you did.

I think the benefits of trying to make a single lib serve all platforms would not outweigh the costs. The platform independent code here is basically a single IF statement (`if unmuted && zoom then mute else if muted and not zoom then unmute`). Everything else is platform dependent, eg the way you detect Zoom, show platform-specific notifications or UI elements, how you package it and activate it, etc.

Probably a better approach is to keep them as separate libraries, where each can do the best for its respective OS, without compromises that a unified API would incur.

I would recommend forking this lib entirely and deleting anything linux related, so it's 100% oriented towards macOS.
